kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: chiz.work.gd
networking:
  apiServerAddress: "172.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"

nodes:
  - role: control-plane
    taints:
      # Под nginx может запускаться при необходимости
      - key: "master_node_may_be"
        value: "nginx"
        effect: "PreferNoSchedule"
      # Все остальные поды не пойдут сюда
      - key: "master_node_newer"
        value: "true"
        effect: "NoSchedule"
  - role: worker
