apiVersion: apps/v1
kind: Deployment
metadata:
  name: chiz-gateway-deployment
  namespace: chiz-work-gd                 # Namespace, где разворачиваем
  labels:
    app: chiz-work-gd-gateway-app        # Лейбл, который используем как селектор для сервиса/Traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chiz-work-gd-gateway-app      # Должен совпадать с лейблом пода
  template:
    metadata:
      labels:
        app: chiz-work-gd-gateway-app
    spec:
      containers:
        - name: gateway
          image: reg.chiz.work.gd/gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002          # Порт внутри контейнера
      imagePullSecrets:
        - name: regcred                   # Секрет для доступа к приватному registry
