apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: traefik-static
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: traefik-static
  hostPath:
    path: /mnt/data/traefik
