
service:
  port: 80
  type: ClusterIP

persistence:
  enabled: true
  storageClassName: grafana-sc
  accessModes:
    - ReadWriteOnce
  size: 300Mi
  annotations: {}

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  extraLabels:
    app: grafana
  paths:
    - /
  pathType: Prefix
  hosts:
    - grafana.chiz.work.gd
  tls:
    - hosts:
        - grafana.chiz.work.gd

adminUser: achi
adminPassword: "123"

extraObjects:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: grafana-sc
    provisioner: kubernetes.io/no-provisioner

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: grafana-pv
    spec:
      capacity:
        storage: 300Mi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Delete
      storageClassName: grafana-sc
      hostPath:
        path: /mnt/data/grafana

#-------------------------------------------------------------

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true
        jsonData:
          timeInterval: "10s"
      - name: Node Exporter
        type: prometheus
        access: proxy
        url: http://prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100
      - name: Kube State Metrics
        type: prometheus
        access: proxy
        url: http://prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 29
      datasource: Prometheus
    kubernetes-cluster-monitoring:
      gnetId: 315
      revision: 2
      datasource: Prometheus
    pods-resources:
      gnetId: 6417
      revision: 1
      datasource: Prometheus

grafana.ini:
  server:
    root_url: https://grafana.chiz.work.gd/
    serve_from_sub_path: true
  security:
    allow_embedding: true
    cookie_secure: true
    cookie_samesite: none