apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-acme-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: traefik-static
  hostPath:
    path: /mnt/data/traefik/acme
