apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-crd-access
rules:
  - apiGroups:
      - "traefik.io"
    resources:
      - traefikservices
      - middlewaretcps
      - serverstransports
      - serverstransporttcps
      - tlsoptions
      - tlsstores
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-crd-access-binding
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: traefik
roleRef:
  kind: ClusterRole
  name: traefik-crd-access
  apiGroup: rbac.authorization.k8s.io
