service:
  type: NodePort

  ports:
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 80
      nodePort: 30001
      protocol: TCP

    websecure:
      port: 8443
      expose:
        default: true
      exposedPort: 443
      nodePort: 30000
      protocol: TCP
      http3:
        enabled: true
      tls:
        enabled: true
        certResolver: letsencrypt

logs:
  general:
    level: DEBUG
  access:
    enabled: true

providers:

  kubernetesIngress:
    enabled: true
  kubernetesGateway:
    enabled: true

gateway:
  enabled: true
  namespacePolicy: All
  entryPoints:
    - web
    - websecure

experimental:
  kubernetesGateway:
    enabled: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "andrey.chizhov.dev@gmail.com"
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
      # tlsChallenge: true

persistence:
  enabled: true
  name: acme-storage
  accessMode: ReadWriteOnce
  size: 10Mi
  storageClass: traefik-static
  path: /data
  annotations:
    helm.sh/resource-policy: keep

api:
  dashboard: true
  insecure: true
