apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/AndreyChiz/chiz.work.gd-GitOps"
        revision: main
        directories:
          - path: cluster/base/* # путь к папкам с приложениями/чартами
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: "https://github.com/AndreyChiz/chiz.work.gd-GitOps"
        targetRevision: main
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
            - custom-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
