apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: base-apps-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: base-applications-storages
            path: cluster/base/base-applications-storages
          - name: grafana
            path: cluster/base/helm-charts/grafana
          - name: prometheus
            path: cluster/base/helm-charts/prometheus
          - name: loki-stack
            path: cluster/base/helm-charts/loki-stack
          - name: alertmanager
            path: cluster/base/helm-charts/prometheus/charts/alertmanager
          - name: metrics-server
            path: cluster/base/helm-charts/metrics-server
          - name: traefik
            path: cluster/base/helm-charts/traefik
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/AndreyChiz/chiz.work.gd-GitOps"
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - custom-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
