apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: https
      port: 443 # внутренний порт сервиса
      targetPort: 443 # порт контейнера Ingress Controller
      nodePort: 30000 # порт ноды, на который будет приходить туннель
    - name: http
      port: 80 # внутренний порт сервиса
      targetPort: 80 # порт контейнера Ingress Controller
      nodePort: 30001 # порт ноды, на который будет приходить туннель
