apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort          # проброс портов наружу
  selector:
    app: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080     # можно выбрать порт для внешнего прокси
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
