apiVersion: v1
kind: ResourceQuota
metadata:
  name: chiz-quota
  namespace: chiz
spec:
  hard:
    pods: "10"
    requests.cpu: "6"
    requests.memory: 1Gi
    limits.cpu: "8"
    limits.memory: 2Gi
