apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik
      initContainers:
        - name: init-acme
          image: busybox
          command:
            [
              "sh",
              "-c",
              "mkdir -p /data && touch /data/acme.json && chmod 600 /data/acme.json",
            ]
          volumeMounts:
            - name: acme
              mountPath: /data
      containers:
        - name: traefik
          image: traefik:v3.5.3
          args:
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"

            - "--providers.kubernetescrd"
            - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
            - "--certificatesresolvers.myresolver.acme.email=andrey.chizhov.dev@gmail.com"
            - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"

            # Логи самого Traefik (внутренняя работа)
            - "--log.level=DEBUG"

            # Access log (каждый запрос)
            - "--accesslog=true"

            # Включить все поля
            - "--accesslog.fields.defaultmode=keep"
            - "--accesslog.fields.headers.defaultmode=keep"

            # Дополнительно выводить:
            - "--accesslog.fields.headers.names.User-Agent=keep"
            - "--accesslog.fields.headers.names.X-Forwarded-For=keep"
            - "--accesslog.fields.headers.names.X-Forwarded-Proto=keep"
            - "--accesslog.fields.headers.names.Host=keep"

            # Включить измерение времени запроса
            - "--accesslog.addInternals=true"

          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          volumeMounts:
            - name: acme
              mountPath: /data
      volumes:
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-acme-pvc
