args:
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --metric-resolution=15s

resources:
  requests:
    cpu: 100m
    memory: 200Mi

tolerations: []
nodeSelector:
  kubernetes.io/os: linux

replicas: 1

service:
  port: 443
