apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "192.168.1.11:6443"

# Сетевой CIDR для Flannel
networking:
  podSubnet: "10.244.0.0/16"

# Репозиторий образов
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers

apiServer:
  certSANs:
    - "192.168.1.11"
    - "127.0.0.1"
    - "kub.chiz.work.gd"

# Игнорируем Swap (через CLI параметр)
# sudo kubeadm init --ignore-preflight-errors=Swap
